=== esraaeliba/XML-projects/employess.dtd
<!ELEMENT employeesList (employee+)>
<!ELEMENT employee (name, phones, addresses, email)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT phones (phone+, phone+)>
<!ELEMENT phone (#PCDATA)>
<!ATTLIST phone type (home | mobile) #REQUIRED>
<!ELEMENT addresses (address+)>
<!ELEMENT address (Street*, BuildingNumber*, Region*, City?, Country?)>
<!ELEMENT Street (#PCDATA)>
<!ELEMENT BuildingNumber (#PCDATA)>
<!ELEMENT Region (#PCDATA)>
<!ELEMENT City (#PCDATA)>
<!ELEMENT Country (#PCDATA)>
<!ELEMENT email (#PCDATA)>

=== esraaeliba/XML-projects/employees.xml
<?xml version="1.0"?>
<!DOCTYPE employeesList SYSTEM "./employess.dtd">
<?xml-stylesheet type="text/css" href="emp.css"?>

<employeesList>
	<employee>
        <name>Name: Esraa Ahmed</name>
        <phones>
            <phone type="home">Home: 4355140</phone>
            <phone type="mobile">Mobile: 01156149108</phone>
        </phones>
        <addresses>
            <address>
                <Street>Street :50 street</Street>
                <BuildingNumber>Building Number : 11</BuildingNumber>
                <Region>Region : West</Region>
                <City>City : Alexancria</City>
                <Country>Country : Alexandria</Country>
            </address>
             <address>
                <Street>Street : 11 street</Street>
                <BuildingNumber>Building Number : 3</BuildingNumber>
                <Region>Region : east</Region>
                <City>City : Alexancria</City>
                <Country>Country : Alexandria</Country>
            </address>
        </addresses>
        <email>Email : esraaeliba@example.com</email>
    </employee>
    
    <employee>
        <name>Name: salmaayman</name>
        <phones>
            <phone type="home">Home: 3544223</phone>
            <phone type="mobile">Mobile: 01077668854</phone>
        </phones>
        <addresses>
            <address> 
                <Street>Street :naal wa handsa street</Street>
                <BuildingNumber>Building Number :23</BuildingNumber>
                <Region>Region : east</Region>
                <City>City : Alexancria</City>
                <Country>Country : Alexandria</Country>
            </address>
        </addresses>
        <email>Email : salmaayman@example.com</email>
    </employee>
    
    
</employeesList>
